#!/bin/bash

wrangler pages dev \
--binding AUTH0_FRONTEND_AUDIENCE=$WORKER_AUTH0_FRONTEND_AUDIENCE \
--binding AUTH0_DOMAIN=$WORKER_AUTH0_DOMAIN \
--binding AUTH0_BACKEND_SECRET=$WORKER_AUTH0_BACKEND_SECRET \
--binding AUTH0_BACKEND_ID=$WORKER_AUTH0_BACKEND_ID \
--binding CF_ACCOUNT_ID=$WORKER_CF_ACCOUNT_ID \
--binding CF_API_TOKEN=$WORKER_CF_API_TOKEN \
-- npm run next:dev